### ISSUE TITLE
Server Crashes when sending it garbage

### ISSUE THREAD

**Issue by monkey1352** [MichaelEpicA/VMBattleRoyale#2]
Client:
```
nc 127.0.0.1 13000
test
```

Server:
```
./VM\ Battle\ Royale\ Server
Setting up test VMBR server...Done.
Waiting for a connection...
New client connected!
0
Unhandled exception. Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: 整. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json)
   at VM_Battle_Royale.Program.RecieveCallBack(IAsyncResult ar) in /home/monkey/SourceCode/vmbattleroyale/VM Battle Royale Server/Program.cs:line 79
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
   at System.Net.Sockets.OverlappedAsyncResult.CompletionCallback(Int32 numBytes, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError errorCode)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.ReadOperation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

the problem is line 79 of the server because the json parser tries to read invalid data

**Comment by monkey1352** [comment]
fixed in commit 3b0705830dc610cc90a57aa2d769ef1a67c976a7
