### ISSUE TITLE
Server Crashes when Client Unexpectedly Disconnects

### ISSUE THREAD

**Issue by monkey1352** [MichaelEpicA/VMBattleRoyale#3]
Client:
```
nc 127.0.0.1 13000
^C
```

Server:
```
./VM\ Battle\ Royale\ Server
Setting up test VMBR server...Done.
Waiting for a connection...
New client connected!
0
Unhandled exception. System.Net.Sockets.SocketException (32): Broken pipe
   at System.Net.Sockets.Socket.Send(Byte[] buffer)
   at VM_Battle_Royale.Program.RecieveCallBack(IAsyncResult ar) in /home/monkey/SourceCode/vmbattleroyale/VM Battle Royale Server/Program.cs:line 76
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback()
   at System.Net.ContextAwareResult.<>c.<Complete>b__15_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionCallback(Int32 numBytes, SocketError errorCode)
   at System.Net.Sockets.OverlappedAsyncResult.CompletionCallback(Int32 numBytes, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError errorCode)
   at System.Net.Sockets.SocketAsyncContext.BufferMemoryReceiveOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncContext.OperationQueue`1.ProcessAsyncOperation(TOperation op)
   at System.Net.Sockets.SocketAsyncContext.ReadOperation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

problem is line 76 of the server where it tries to send data to the connected client

**Comment by monkey1352** [comment]
fixed in commit 7c18d32ce2484b2a397e48ba4670656a9b2ada9c
